version: '3.4'

services:
  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  mysql-dev:
    image: mysql/mysql-server
    container_name: db
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql-db:

networks:
  default:
    external:
      name: dev
