version: '3.4'

services:
  mysql:
    image: mysql/mysql-server
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql-db:

networks:
  default:
    external:
      name: jenkins-testing
